<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VendorSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();
        $featuredStart = $now;
        $featuredEnd = Carbon::create(2099, 12, 31);

        $vendors = [

            // ------------------------
            // 1. Stage & Decoration
            // ------------------------
            [
                "vendor_name" => "Rama-Rama Wedding Deco",
                "category" => "Stage & Decoration",
                "description" => "Affordable pelamin and wedding décor provider based in Cheras.",
                "starting_price" => 1500.00,
                "phone" => "+60 17-889 3321",
                "email" => "info@ramaramaevent.com",
                "address" => null,
                "city" => "Cheras",
                "state" => "Klang Valley",
                "postcode" => null,
                "logo_url" => "https://ramaramaevent.com/logo.png",
                "banner_url" => "https://ramaramaevent.com/banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "vendor_name" => "The Calla Wedding Decor",
                "category" => "Stage & Decoration",
                "description" => "Luxury wedding décor studio offering premium floral & pelamin concepts.",
                "starting_price" => 6800.00,
                "phone" => "+60 12-889 1123",
                "email" => "contact@thecallastudio.my",
                "address" => null,
                "city" => "Bukit Damansara",
                "state" => "Kuala Lumpur",
                "postcode" => null,
                "logo_url" => "https://thecallastudio.my/logo.png",
                "banner_url" => "https://thecallastudio.my/banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],

            // ------------------------
            // 2. Attire & Makeup
            // ------------------------
            [
                "vendor_name" => "Makeup by Nadira",
                "category" => "Attire & Makeup",
                "description" => "Professional bridal makeup artist based in Cheras.",
                "starting_price" => 1200.00,
                "phone" => "+60 11-8812 5221",
                "email" => "nadiramakeup@gmail.com",
                "address" => null,
                "city" => "Cheras",
                "state" => "Selangor",
                "postcode" => null,
                "logo_url" => "https://example.com/nadira-makeup-logo.jpg",
                "banner_url" => "https://example.com/nadira-makeup-banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "vendor_name" => "Rizman Ruzaini Bridal",
                "category" => "Attire & Makeup",
                "description" => "High-end couture bridal attire & premium makeover services.",
                "starting_price" => 8500.00,
                "phone" => "+60 12-333 8991",
                "email" => "bridal@rizmanruzaini.my",
                "address" => null,
                "city" => "Bukit Bintang",
                "state" => "Kuala Lumpur",
                "postcode" => null,
                "logo_url" => "https://rizmanruzaini.my/logo.png",
                "banner_url" => "https://rizmanruzaini.my/banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],

            // ------------------------
            // 3. Photography & Videography
            // ------------------------
            [
                "vendor_name" => "Lensaku Studios",
                "category" => "Photography & Videography",
                "description" => "Affordable photography studio in PJ specialising in candid captures.",
                "starting_price" => 2000.00,
                "phone" => "+60 14-667 1933",
                "email" => "hello@lensaku.my",
                "address" => null,
                "city" => "Petaling Jaya",
                "state" => "Klang Valley",
                "postcode" => null,
                "logo_url" => "https://lensaku.my/logo.png",
                "banner_url" => "https://lensaku.my/banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "vendor_name" => "The Photoz",
                "category" => "Photography & Videography",
                "description" => "Premium cinematic wedding films & portraiture studio.",
                "starting_price" => 9500.00,
                "phone" => "+60 12-778 3321",
                "email" => "studio@thephotoz.com",
                "address" => null,
                "city" => "Mont Kiara",
                "state" => "Kuala Lumpur",
                "postcode" => null,
                "logo_url" => "https://thephotoz.com/logo.png",
                "banner_url" => "https://thephotoz.com/banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],

            // ------------------------
            // 4. Catering
            // ------------------------
            [
                "vendor_name" => "Dapur Mak Andam Catering",
                "category" => "Catering",
                "description" => "Home-style Malay dishes ideal for intimate weddings.",
                "starting_price" => 12.90,
                "phone" => "+60 17-912 8873",
                "email" => "order@dapurmakandam.my",
                "address" => null,
                "city" => "Cheras",
                "state" => "Selangor",
                "postcode" => null,
                "logo_url" => "https://example.com/dapur-logo.jpg",
                "banner_url" => "https://example.com/dapur-banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "vendor_name" => "Big Onion Food Caterer",
                "category" => "Catering",
                "description" => "Premium caterer offering luxury cuisine & live stations.",
                "starting_price" => 58.00,
                "phone" => "+60 3-7772 1919",
                "email" => "sales@bigonion.com.my",
                "address" => null,
                "city" => "Petaling Jaya",
                "state" => "Klang Valley",
                "postcode" => null,
                "logo_url" => "https://bigonion.com.my/logo.png",
                "banner_url" => "https://bigonion.com.my/banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],

            // ------------------------
            // 5. Venue & Canopy
            // ------------------------
            [
                "vendor_name" => "Dewan Komuniti Cheras",
                "category" => "Venue & Canopy",
                "description" => "Budget-friendly hall located in Cheras for up to 500 guests.",
                "starting_price" => 1200.00,
                "phone" => "+60 13-225 9191",
                "email" => "info@cherashall.gov.my",
                "address" => "Jalan 2/90, Taman Shamelin Perkasa",
                "city" => "Cheras",
                "state" => "Kuala Lumpur",
                "postcode" => "56100",
                "logo_url" => "https://example.com/dewan-logo.png",
                "banner_url" => "https://example.com/dewan-banner.png",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "vendor_name" => "Glasshouse Seputeh",
                "category" => "Venue & Canopy",
                "description" => "Premium glass-architecture wedding venue with lush greenery.",
                "starting_price" => 15000.00,
                "phone" => "+60 12-287 8892",
                "email" => "hello@glasshouseseputeh.com",
                "address" => "336, Jalan Kelang Lama",
                "city" => "Seputeh",
                "state" => "Kuala Lumpur",
                "postcode" => "58100",
                "logo_url" => "https://glasshouseseputeh.com/assets/logo.png",
                "banner_url" => "https://glasshouseseputeh.com/assets/header.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],

            // ------------------------
            // 6. Entertainment & Kompang
            // ------------------------
            [
                "vendor_name" => "Kompang Seri Wawasan",
                "category" => "Entertainment & Kompang",
                "description" => "Traditional kompang group based in Selangor.",
                "starting_price" => 650.00,
                "phone" => "+60 19-822 9090",
                "email" => "seriwawasan@gmail.com",
                "address" => null,
                "city" => "Ampang",
                "state" => "Selangor",
                "postcode" => null,
                "logo_url" => "https://example.com/kompang-logo.jpg",
                "banner_url" => "https://example.com/kompang-banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "vendor_name" => "The KL Live Band",
                "category" => "Entertainment & Kompang",
                "description" => "Premium wedding live band located in KL City.",
                "starting_price" => 7800.00,
                "phone" => "+60 11-2212 8765",
                "email" => "booking@klliveband.com",
                "address" => null,
                "city" => "KL City Centre",
                "state" => "Kuala Lumpur",
                "postcode" => null,
                "logo_url" => "https://klliveband.com/logo.png",
                "banner_url" => "https://klliveband.com/banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],

            // ------------------------
            // 7. Wedding Planner
            // ------------------------
            [
                "vendor_name" => "WN Wedding Planner",
                "category" => "Wedding Planner",
                "description" => "Budget-friendly wedding planner specialising in basic styling.",
                "starting_price" => 2500.00,
                "phone" => "+60 16-223 7171",
                "email" => "contact@wnwedding.my",
                "address" => null,
                "city" => "Cheras",
                "state" => "Selangor",
                "postcode" => null,
                "logo_url" => "https://example.com/wn-logo.jpg",
                "banner_url" => "https://example.com/wn-banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "vendor_name" => "Ibunda Wedding & Events",
                "category" => "Wedding Planner",
                "description" => "Exclusive luxury wedding planner offering full coordination.",
                "starting_price" => 12000.00,
                "phone" => "+60 17-778 3232",
                "email" => "hello@ibundawedding.com",
                "address" => null,
                "city" => "Bangsar",
                "state" => "Kuala Lumpur",
                "postcode" => null,
                "logo_url" => "https://ibundawedding.com/logo.png",
                "banner_url" => "https://ibundawedding.com/banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],

            // ------------------------
            // 8. Invitations & Doorgifts
            // ------------------------
            [
                "vendor_name" => "KadKahwin Cheras",
                "category" => "Invitations & Doorgifts",
                "description" => "Affordable wedding invitations & digital e-cards.",
                "starting_price" => 0.80,
                "phone" => "+60 13-771 1129",
                "email" => "hello@kadkahwincheras.my",
                "address" => null,
                "city" => "Cheras",
                "state" => "Selangor",
                "postcode" => null,
                "logo_url" => "https://example.com/kadkahwin-logo.jpg",
                "banner_url" => "https://example.com/kadkahwin-banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "vendor_name" => "The Wedding Notebooks",
                "category" => "Invitations & Doorgifts",
                "description" => "Luxury custom wedding invitations & artisan doorgifts.",
                "starting_price" => 3.50,
                "phone" => "+60 12-661 6678",
                "email" => "studio@weddingnotebooks.com",
                "address" => null,
                "city" => "Petaling Jaya",
                "state" => "Klang Valley",
                "postcode" => null,
                "logo_url" => "https://weddingnotebooks.com/logo.png",
                "banner_url" => "https://weddingnotebooks.com/banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],

            // ------------------------
            // 9. Transportation
            // ------------------------
            [
                "vendor_name" => "Cheras Wedding Car Rental",
                "category" => "Transportation",
                "description" => "Affordable wedding car rental for akad nikah & reception.",
                "starting_price" => 350.00,
                "phone" => "+60 14-887 2231",
                "email" => "booking@cherasweddingcar.my",
                "address" => null,
                "city" => "Cheras",
                "state" => "Selangor",
                "postcode" => null,
                "logo_url" => "https://example.com/cheras-car-logo.jpg",
                "banner_url" => "https://example.com/cheras-car-banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],
            [
                "vendor_name" => "MyWedding Chauffeur KL",
                "category" => "Transportation",
                "description" => "Luxury chauffeur service offering Mercedes & BMW.",
                "starting_price" => 2800.00,
                "phone" => "+60 11-7881 3321",
                "email" => "info@myweddingchauffeur.com",
                "address" => null,
                "city" => "KL City",
                "state" => "Kuala Lumpur",
                "postcode" => null,
                "logo_url" => "https://myweddingchauffeur.com/logo.png",
                "banner_url" => "https://myweddingchauffeur.com/banner.jpg",
                "gallery" => json_encode([]),
                "created_by_type" => "admin",
                "created_by_id" => 1,
                "is_featured" => true,
                "featured_start" => $featuredStart,
                "featured_end" => $featuredEnd,
                "rating_average" => 0,
                "rating_count" => 0,
                "status" => "active",
                "created_at" => $now,
                "updated_at" => $now,
            ],

        ];

        DB::table('vendors')->insert($vendors);
    }
}
